name: SmartParking
options:
  bundleIdPrefix: com.andresmorales
  deploymentTarget:
    iOS: "17.0"
targets:
  SmartParking:
    type: application
    platform: iOS
    sources:
      - path: SmartParking
    info:
      path: SmartParking/Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andresmorales.SmartParking
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets: []
schemes:
  SmartParking:
    build:
      targets:
        SmartParking: all
    run:
      config: Debug
    archive:
      config: Release
